### ISSUE TITLE
Missing optional argument in channels.list

### ISSUE THREAD

**Issue by raveious** [os/slacker#104]
There is a new addition to the channels.list method which excludes the members of each channel, this is for faster return times on this methods for larger teams.

https://api.slack.com/methods/channels.list

**Comment by simonsolnes** [comment]
Fixed: [https://github.com/os/slacker/commit/86706036ed4ba1c3e05ea945eb8bd14d53f9cfc4](https://github.com/os/slacker/commit/86706036ed4ba1c3e05ea945eb8bd14d53f9cfc4)
