### ISSUE TITLE
Error in the pip installation (Windows)

### ISSUE THREAD

**Issue by COLAMAroro** [os/slacker#109]
Just doing pip install slacker raised me this error;

http://i.imgur.com/j1YmY0P.png

File version is linked
[Slacker traceback.txt](https://github.com/os/slacker/files/1020353/Slacker.traceback.txt)

**Comment by frostbtn** [comment]
It's `slacker`, not `stacker`. Stackers don't slack, and slackers don't stack.

**Comment by COLAMAroro** [comment]
Huh, it looks like the bug is between the screen and the chair

Thank you
