### ISSUE TITLE
Thread broadcasting

### ISSUE THREAD

**Issue by raveious** [os/slacker#113]
When posting using chat.post_message, you can set the "thread_ts" field to create a thread. There is another ability to post the message back into the channel by setting the reply_broadcast field to true.

https://api.slack.com/docs/message-threading

**Comment by jonathanchan** [comment]
should this be mark closed now? reply_broadcast is part of chat.post_message.

https://github.com/os/slacker/blob/master/slacker/__init__.py#L491

**Comment by raveious** [comment]
It wasn't implemented at the time.
