### ISSUE TITLE
im.history error - channel_not_found

### ISSUE THREAD

**Issue by kthouz** [os/slacker#125]
I am trying to get history of im. When I run
```
slack.im.history(channel='<channel_id>')
```
I get an error "channel_not_found".

My question is what should I put as channel?
 Channel name or id? Due to lack of documentation, I am not being able to have this running right.

**Comment by os** [comment]
Hi @kthouz. Sorry for the late reply, I've been busy with so many other things. It's the channel ID, see official documentation https://api.slack.com/methods/im.history.
