### ISSUE TITLE
Slack Token? Webhook URL?

### ISSUE THREAD

**Issue by caliph007** [os/slacker#138]
I am trying to setup and cannot see any token generation for channels on slack.

It seems slack has a Webhook URL.

And I see legacy tokens, that are to be depreciated. And slack discourages from using it.

What token is necessary for slacker?

**Comment by talaniz** [comment]
This section details webhook urls-- https://api.slack.com/incoming-webhooks. This section covers the different token types-- https://api.slack.com/docs/token-types. It looks like the token you use depends on how you want to interact with Slack. 

From the Slack docs--
- User tokens allow you to work directly on behalf of users, based on the OAuth scopes they award to your app.
- Bot user tokens are special and require a bot user and the bot scope.
- Workspace tokens are part of our team-based Slack apps developer preview. They are agents for everything your app can do for a particular team.
- Legacy tokens, scopes, and methods are better left to the past.
- Verification tokens aren't like other tokens. Use them to validate requests coming from Slack.

According to issue #91 I can see a proposed usage was the following--

```
slack = Slacker('<token>', incoming_webhook_url='<response_url>')
slack.incomingwebhook.post({"text": "It's 80 degrees right now."})
```

Based on this, I would say that you will most likely want either a `user`, `bot` or `workspace` token as `legacy` is discouraged (as noted) and `verification` validates requests _from_ Slack. Based on what I see in the code, it looks like you wouldn't be required to  use one as both examples provided don't use them (though an example may be worthwhile). Here's line 14/15 from `list.py`--

```
token = os.environ['SLACK_TOKEN']
slack = Slacker(token)
```

**Comment by os** [comment]
Thanks, @talaniz!
