### ISSUE TITLE
Renaming in 0.13 breaks slacker-cli

### ISSUE THREAD

**Issue by billygout** [os/slacker#153]
As I've reported at https://github.com/juanpabloaj/slacker-cli/issues/33, The renaming of `utils` to `utilities` in release 0.13 has broken slacker-cli.

**Comment by hugovk** [comment]
Please see https://github.com/juanpabloaj/slacker-cli/pull/35 for a fix.

**Comment by os** [comment]
Thanks for this, @billygout. Even though we try our best not to we might release some breaking changes in time to time, so it's better to specify the version in your requirements instead. We're not going to address this so I'm closing this issue.
