### ISSUE TITLE
Fedora package

### ISSUE THREAD

**Issue by rapgro** [os/slacker#154]
Hi,
let me kindly announce official packages available in the Fedora repository, currently for Rawhide, F30 and EPEL7 (latter as addon for RHEL7/CentOS7). I'm the proud maintainer of both packages named slack-cleaner and python-slacker (as dependency).
Commands to install:
```
# Fedora
dnf install python3-slacker
# EPEL7
yum install -y epel-release ; yum install python36-slacker
```
Please be aware about Python 2 will not be supported as there's official and general EOL announced.

Regards.

See also https://github.com/sgratzl/slack-cleaner/issues/51

**Comment by os** [comment]
Thanks, @rapgro. I'm closing this issue as there's no action to be taken.
