### ISSUE TITLE
RTM support?

### ISSUE THREAD

**Issue by seancron** [os/slacker#17]
Any plans for adding more support for the [RTM API](https://api.slack.com/rtm)?

Let me know if I can help at all.

**Comment by bcicen** [comment]
Slacker does have the RTM resource to fetch a websocket url; are you referring to integrating some type of websocket streaming?

**Comment by prongs** [comment]
Yes, a framework for continuous read and handling of events

**Comment by bcicen** [comment]
[SlackSocket](https://github.com/bcicen/slacksocket) supports all RTM functionality + user/channel ID translation to human-readable names.
