### ISSUE TITLE
InsecurePlatformWarning: A true SSLContext object is not available

### ISSUE THREAD

**Issue by juanpabloaj** [os/slacker#25]
When I try to post a message I get this warning

```python
In [1]: from slacker import Slacker
In [2]: slack = Slacker('abc-123')
In [3]: slack.chat.post_message('#random', 'hello from slacker')
/Users/pablo/envs/slacker-cli/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79:
InsecurePlatformWarning: A true SSLContext object is not available.
This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail.
For more information, see
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Out[3]: <slacker.Response object at 0x107726350>
```

**Comment by os** [comment]
Messages are still going through. See the [original issue](https://github.com/kennethreitz/requests/issues/2214). I'm not sure if we should suppress these warnings in *slacker*.

**Comment by os** [comment]
Messages are still going through. See the [original issue](https://github.com/kennethreitz/requests/issues/2214). I'm not sure if we should suppress these warnings in *slacker*.

**Comment by juanpabloaj** [comment]
I never see this message before

I thought this message was related with the recent security incident in slack 

http://slackhq.com/post/114696167740/march-2015-security-incident-and-launch-of-2fa

**Comment by os** [comment]
It's not related. You wouldn't see any of these warnings if you follow the same steps with requests==2.2.1.

**Comment by os** [comment]
The question is, should we suppress these warnings?

**Comment by juanpabloaj** [comment]
In a library like slacker, I think it is not necessary suppress the warnings, because the developer who use the library can ignore these. 
what is your opinion ?

in the case of a command line application like https://github.com/juanpabloaj/slacker-cli , I think it is necessary suppress the warning messages.

**Comment by os** [comment]
Yeah, that's what I was thinking too. Thanks for the ticket @juanpabloaj.
