### ISSUE TITLE
Cannot upload files

### ISSUE THREAD

**Issue by codehive** [os/slacker#26]
# Upload a file
slack.files.upload('rtmbot.conf')

This does not work for me.

I get slacker.Error: user_is_bot

**Comment by bcicen** [comment]
The error you're getting is described in the [docs](https://api.slack.com/methods/files.upload). You need to be authenticated with a user token, not an integration or bot token.

**Comment by os** [comment]
I think we can close this ticket. Thanks @bcicen.
