### ISSUE TITLE
File upload not working with unicode characters

### ISSUE THREAD

**Issue by abbeycode** [os/slacker#31]
Calling `slack.files.upload('File 1.txt')` will work, but `slack.files.upload('File ∑.txt')` gives the following error:

>slacker.Error: no_file_data

I'm using Python 3

**Comment by os** [comment]
Just tried with cURL and it worked. This could be an issue with requests https://github.com/kennethreitz/requests/issues/2411

**Comment by abbeycode** [comment]
Thanks, it definitely looks like that's the case (though more accurately, Slack isn't properly handling an RFC standard that Requests implements). I'm taking it up with Slack.
