### ISSUE TITLE
CGI.escape() kills inline slack codes in chat.post_message

### ISSUE THREAD

**Issue by theodox** [os/slacker#33]
Messages posted using `chat.post_message()` are run through `cgi.escape()`.  This suppresses any internal angle brackets, which means you can't use the [slack api formatting conventions](https://api.slack.com/docs/formatting) for things like inline links or user references.  

It should be pretty easy to add a flag to post_message that disables escaping, or something more clever that runs escape (to get rid of quotes and so on) then re-instates angle-brackets that look like slack commands

**Comment by os** [comment]
@theodox Thanks, I'll look into this.

**Comment by os** [comment]
It is now working as expected after a39f33a820e588ca71abb810577a400189d97f57.
