### ISSUE TITLE
Trying to upload a txt file

### ISSUE THREAD

**Issue by ElzWhere** [os/slacker#44]
I'm trying to upload a local txt file to a channel 
slack.files.upload('blah.txt', channels='channelname'')

am I doing something wrong here.

**Comment by os** [comment]
@ElzWhere You need to pass a channel ID (get the channel ID with https://api.slack.com/methods/channels.list), not a channel name. See https://api.slack.com/methods/files.upload.

**Comment by os** [comment]
You could also use the helper function `Channel.get_channel_id`. e.g. `slack.files.upload('blah.txt', channels=slack.channels.get_channel_id('channelname'))`
