### ISSUE TITLE
Add __version__

### ISSUE THREAD

**Issue by zachsnow** [os/slacker#60]
Very minor, would be convenient to have `slacker.__version__` as in https://www.python.org/dev/peps/pep-0396/

**Comment by os** [comment]
Thanks, @zachsnow. I'll add that once I get a chance.

**Comment by simonsolnes** [comment]
[https://github.com/os/slacker/commit/56e42f47232113ffdfb525f5c72923dce17350ef](https://github.com/os/slacker/commit/56e42f47232113ffdfb525f5c72923dce17350ef)
