### ISSUE TITLE
Persistent connection issue

### ISSUE THREAD

**Issue by forstmeier** [os/slacker#61]
I've been unable to fully establish a persistent connections to Slack so that the bot appears as "Active" in the DM list. This functionality is available in the official Slack Python library but I can't seem to get it to work here.

**Comment by os** [comment]
You can't create persistent connections through [API Methods](https://api.slack.com/methods). To create persistent connections you need to look at [Real Time Messaging API](https://api.slack.com/rtm) and WebSockets. Slacker doesn't support RTM functionality, so you might want to look at projects like [Slacksocket](https://github.com/vektorlab/slacksocket).
