### ISSUE TITLE
Support to deactivate a user

### ISSUE THREAD

**Issue by markaltmann** [os/slacker#66]
Is it possible to invite/deactivate users via slacker / slack api?
Also unfortunately i haven't seen anything regarding that.

Under: https://api.slack.com/methods there is also no mention of the user on/offboarding procedure.

thx.

**Comment by os** [comment]
You might want to look at [channels.invite](https://api.slack.com/methods/channels.invite) and [channels.kick](https://api.slack.com/methods/channels.kick methods). You can get better answers on your product related questions from https://github.com/slackhq/slack-api-docs.
