### ISSUE TITLE
Can't send attachments through using post_message

### ISSUE THREAD

**Issue by LukeNZ** [os/slacker#67]
I don't have a clue about what's going on here, and honestly I can't tell if it's Slack, Slacker, or my issue:

		attachmentdata = json.dumps(
			{
				"attachments": [
					{
						"fallback": fallback_message,
						"color": "#ccac55",

						"title": "New {}: {}".format("selfpost" if submission.is_self == True else "link post", submission.title),
						"title_link": RedditService.create_shortlink(submission.id),

						"text": submission.title,

						"fields": [
							{
								"title": "Domain",
								"value": submission.domain,
								"short": True
							},
							{
								"title": "Author",
								"value": "/u/{}".format(submission.author),
								"short": True
							}
						],

						"thumb_url": submission.thumbnail,

						"footer": "r/SpaceX",
						"footer_icon": "https://spacexstats.com/favicon-194x194.png",
						"ts": int(submission.created_utc)
					}
				]
			}
		)

		print(attachmentdata)

		self.slack.chat.post_message('#newposts', "test", as_user=True, attachments=attachmentdata, unfurl_links=True, unfurl_media=True)

This JSON compiles to:

     {"attachments": [{"ts": 1465565991.0, "title_link": "https://redd.it/4ngbu1", "thumb_url": "http://b.thumbs.redditmedia.com/whD2TBHwdLh4WUOQwNl4AFCidqv1Z5QM41rZdC4DNcU.jpg", "text": "dddd", "fallback": "[r/SpaceX] New link post: dddd by /u/EchoLogic https://redd.it/4ngbu1", "footer": "r/SpaceX", "fields": [{"short": true, "value": "reddit.com", "title": "Domain"}, {"short": true, "value": "/u/EchoLogic", "title": "Author"}], "title": "New link post: dddd", "color": "#ccac55", "footer_icon": "https://spacexstats.com/favicon-194x194.png"}]}

Yet, when submitted through using the API, the attachment simply does not appear. If I remove the `"text"` parameter of `post_message`, I get a Slack `no_text` error, which violates their API design:

> A message must have either text or attachments or both. The text parameter is required unless you provide attachments. You can use both parameters in conjunction with each other to create awesome messages.

What's the deal here?

**Comment by supasimu** [comment]
The toplevel "attachments" key is added by slacker. Thus your request will be sent off like as `{"attachments": { "attachments" : [ *actual attachment* ] } ] }`, which will be ignored by the slack API.
This is how your `attachmentdata` should look:
```
attachmentdata = json.dumps(
        [
            {
                "fallback": fallback_message,
                "color": "#ccac55",

                "title": "New {}: {}".format("selfpost" if submission.is_self == True else "link post", submission.title),
                "title_link": RedditService.create_shortlink(submission.id),

                "text": submission.title,

                "fields": [
                    {
                        "title": "Domain",
                        "value": submission.domain,
                        "short": True
                    },
                    {
                        "title": "Author",
                        "value": "/u/{}".format(submission.author),
                        "short": True
                    }
                ],

                "thumb_url": submission.thumbnail,

                "footer": "r/SpaceX",
                "footer_icon": "https://spacexstats.com/favicon-194x194.png",
                "ts": int(submission.created_utc)
            }
        ]
    )
```

**Comment by os** [comment]
Thanks @supasimu. @LukeNZ Is your problem solved?

**Comment by technicalpickles** [comment]
I've run into this as well. Consider this call:

    attachments =  [{'image_url': 'http://i.imgur.com/JEExnsI.gif', 'title': 'what a terrible night to have a curse'}]
    self.slack.chat.post_message('#random', "test", as_user=True, attachments=attachmentdata)

Looking at the code, it should `json.dumps` for you. I cloned the repo to add some debugging, and confirmed that the attachment data gets down into `chat.post_message`, and also the `BaseAPI._request` method.

Despite that, the attachment isn't going through. The API call succeeds, and the "test" message is sent, but there is no attachment. 

Also worth noting that in https://api.slack.com/methods/chat.postMessage `text` should be optional if you pass in attachments.

**Comment by technicalpickles** [comment]
Actually, it seems the data for `chat.postMessage` needs to be passed as parameters rather as form encoded data. Once I did that, the attachment went through. I'll make a PR with those changes.

**Comment by technicalpickles** [comment]
https://github.com/os/slacker/pull/75 fixes the problem I described
