### ISSUE TITLE
should response.successful != True yield an exception?

### ISSUE THREAD

**Issue by SoCalLongboard** [os/slacker#68]
On lines 61-62 in slacker/**init**.py, you raise an exception where response.successful != True. In the WebAPI implementation, the response would simply be yielded with 'ok': 'False' and 'error': '[some error message]'. Wouldn't it make more sense to mimic the WebAPI implementation in this respect and just yield the response as-is?  Thanks!

**Comment by os** [comment]
That was a design decision back then. I can't think of a scenario where this may cause issues with your integration. Can you give me an example?
