### ISSUE TITLE
chat.post_message() arguments does not match SlackApi arguments

### ISSUE THREAD

**Issue by MisterHoker** [os/slacker#83]
I was faced with next problem: 
When I try to send message with attachments and without text I'm catching exception
But Slack provides sending message with empty text and attachments, as you can see picture below
![image](https://cloud.githubusercontent.com/assets/14099097/19181367/488fcdd4-8c75-11e6-8a76-dea742b4a113.png)
Hope you fix that:)

**Comment by tomdownes14** [comment]
You can provide a string with just a space as the text field, which is then overridden by your attachments. I've done this and had no issues.

**Comment by nmavor** [comment]
HI
i just test it and its not looking as working 
the code is :

from slacker import Slacker

slack = Slacker(properties.slack_key)
MSG = '[{title:"cnn site", title_link:"httpcnn.com"}]'
slack.chat.post_message(channel='test',attachments=MSG,text=' ')

i did test full json but its not working in geting clear text in the slack

**Comment by JWSong** [comment]
You must put a wrong-formatted attachment. If a wrong-formatted attachment sent to API, it is ignored so that the 'text' field is required. Check your attachment format and do not forget set the argument 'text' to None.
