### ISSUE TITLE
Add users.admin.invite

### ISSUE THREAD

**Issue by nikdatrix** [os/slacker#86]
not documented api method.
check : https://github.com/ErikKalkoken/slackApiDoc/blob/master/users.admin.invite.md
and: https://twitter.com/slackapi/status/570323011338772480

**Comment by simonsolnes** [comment]
[https://github.com/os/slacker/commit/1b193933e1f853fd9d50be7f7205476b257bbff7](https://github.com/os/slacker/commit/1b193933e1f853fd9d50be7f7205476b257bbff7)
