### ISSUE TITLE
Python package trove classifiers aren't showing up on PyPI

### ISSUE THREAD

**Issue by tveastman** [os/slacker#87]
Hi!

Your `setup.py` contains trove classifiers, but they aren't showing up on slacker's PyPI page for some reason:

https://pypi.python.org/pypi/slacker/0.9.29

I don't know why not, maybe it's as simple as that fact that your classifiers are in a tuple and not a list?

The classifiers not showing means that tools like `caniusepython3` list slacker as "not supporting Python 3" when the code, and travis configuration, suggests that it does.

**Comment by os** [comment]
Thanks @tveastman!
