### ISSUE TITLE
 "Slack API Tester" -- rename

### ISSUE THREAD

**Issue by GildedHonour** [os/slacker#99]
When I post a message to a channel, it posts it under the name "Slack API Tester". How can I setup it up or rename?

**Comment by sughodke** [comment]
Create a Slack App and authorize it to your Organization's Slack.  Creating the App will let you naming it, etc.  (Authorizing your App will generate a Token, use that in Slacker)

https://api.slack.com/slack-apps
https://api.slack.com/custom-integrations/legacy-tokens

**Comment by Neurobion** [comment]
That's true but it raise an [exception](https://github.com/kfei/slack-cleaner/issues/36).

**Comment by simonsolnes** [comment]
When using `slacker.chat.post_message()` pass the arugment `as_user = True` to send it from yourself, or `username = "foobar"` to set the username.
